In [1]:
import numpy as np
import PySeqArray as ps
import pandas

Open a SeqArray file and display its structure

In [2]:
fn = ps.get_example_path('1KG_phase1_release_v3_chr22.gds')
f = ps.SeqArrayFile()
f.open(fn)
f.show()

File: /Users/sts/anaconda/lib/python3.6/site-packages/PySeqArray/data/1KG_phase1_release_v3_chr22.gds (1.1M)
+    [  ] *
|--+ description   [  ] *
|--+ sample.id   { Str8 1092 LZMA_ra(10.5%), 914B } *
|--+ variant.id   { Int32 19773 LZMA_ra(8.39%), 6.5K } *
|--+ position   { Int32 19773 LZMA_ra(52.0%), 40.1K } *
|--+ chromosome   { Str8 19773 LZMA_ra(0.28%), 166B } *
|--+ allele   { Str8 19773 LZMA_ra(22.7%), 109.2K } *
|--+ genotype   [  ] *
|  |--+ data   { Bit2 19773x1092x2 LZMA_ra(8.17%), 861.8K } *
|  |--+ extra.index   { Int32 0x3 LZMA_ra, 19B } *
|  \--+ extra   { Int16 0 LZMA_ra, 19B }
|--+ phase   [  ]
|  |--+ data   { Bit1 19773x1092 LZMA_ra(0.02%), 550B } *
|  |--+ extra.index   { Int32 0x3 LZMA_ra, 19B } *
|  \--+ extra   { Bit1 0 LZMA_ra, 19B }
|--+ annotation   [  ]
|  |--+ id   { Str8 19773 LZMA_ra(35.2%), 75.2K } *
|  |--+ qual   { Float32 19773 LZMA_ra(3.62%), 2.8K } *
|  |--+ filter   { Int32,factor 19773 LZMA_ra(0.21%), 170B } *
|  |--+ info   [  ]
|  \--+ format   [

In [3]:
sampid = f.GetData("sample.id")
sampid

array(['HG00096', 'HG00097', 'HG00099', ..., 'NA20819', 'NA20826',
       'NA20828'], dtype=object)

In [4]:
varid = f.GetData("variant.id")
varid

array([    1,     2,     3, ..., 19771, 19772, 19773], dtype=int32)

In [5]:
f.FilterSet(sample_id = sampid[:16])
f.FilterSet(variant_id = varid[:32])

In [6]:
f.GetData("chromosome")

array(['22', '22', '22', '22', '22', '22', '22', '22', '22', '22', '22',
       '22', '22', '22', '22', '22', '22', '22', '22', '22', '22', '22',
       '22', '22', '22', '22', '22', '22', '22', '22', '22', '22'], dtype=object)

In [7]:
f.GetData("allele")

array(['A,G', 'G,A', 'G,T', 'C,T', 'G,A', 'G,A', 'G,A',
       'ATATTTTCTGCACATATT,A', 'GT,G', 'G,A', 'T,C', 'C,T', 'G,A', 'C,T',
       'G,A', 'C,A', 'A,ATTT', 'G,A', 'C,A', 'G,C', 'G,A', 'T,C', 'C,A',
       'C,T', 'T,A', 'C,T', 'A,G', 'T,C', 'C,G', 'A,G', 'C,T', 'T,C'], dtype=object)

In [9]:
g = f.GetData("genotype")
g

array([[[0, 0],
        [1, 0],
        [1, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 1]],

       [[0, 0],
        [0, 1],
        [0, 1],
        ..., 
        [0, 0],
        [0, 1],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]],

       ..., 
       [[0, 0],
        [1, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=uint8)

In [10]:
g.shape

(32, 16, 2)

In [11]:
g = f.GetData("$dosage")
g

array([[2, 1, 1, 1, 1, 1, 2, 2, 1, 0, 1, 1, 0, 2, 2, 1],
       [2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2,

In [12]:
g.shape

(32, 16)