# Python tutorial with SeqArray files

In [1]:
import numpy as np
import PySeqArray as ps
import pandas

Open a SeqArray file and display its structure

In [2]:
fn = ps.get_example_path('1KG_phase1_release_v3_chr22.gds')
f = ps.SeqArrayFile()
f.open(fn)
f.show()

File: /Users/sts/anaconda/lib/python3.6/site-packages/PySeqArray/data/1KG_phase1_release_v3_chr22.gds (1.1M)
+    [  ] *
|--+ description   [  ] *
|--+ sample.id   { Str8 1092 LZMA_ra(10.5%), 914B } *
|--+ variant.id   { Int32 19773 LZMA_ra(8.39%), 6.5K } *
|--+ position   { Int32 19773 LZMA_ra(52.0%), 40.1K } *
|--+ chromosome   { Str8 19773 LZMA_ra(0.28%), 166B } *
|--+ allele   { Str8 19773 LZMA_ra(22.7%), 109.2K } *
|--+ genotype   [  ] *
|  |--+ data   { Bit2 19773x1092x2 LZMA_ra(8.17%), 861.8K } *
|  |--+ extra.index   { Int32 0x3 LZMA_ra, 19B } *
|  \--+ extra   { Int16 0 LZMA_ra, 19B }
|--+ phase   [  ]
|  |--+ data   { Bit1 19773x1092 LZMA_ra(0.02%), 550B } *
|  |--+ extra.index   { Int32 0x3 LZMA_ra, 19B } *
|  \--+ extra   { Bit1 0 LZMA_ra, 19B }
|--+ annotation   [  ]
|  |--+ id   { Str8 19773 LZMA_ra(35.2%), 75.2K } *
|  |--+ qual   { Float32 19773 LZMA_ra(3.62%), 2.8K } *
|  |--+ filter   { Int32,factor 19773 LZMA_ra(0.21%), 170B } *
|  |--+ info   [  ]
|  \--+ format   [

The dimensions of `sample.id` and `variant.id` tell you the total numbers of samples and variants.

In [3]:
sampid = f.GetData("sample.id")
sampid  # a list of sample IDs

array(['HG00096', 'HG00097', 'HG00099', ..., 'NA20819', 'NA20826',
       'NA20828'], dtype=object)

In [4]:
varid = f.GetData("variant.id")
varid  # a list of variant IDs

array([    1,     2,     3, ..., 19771, 19772, 19773], dtype=int32)

Define a subset of samples and variants

In [5]:
f.FilterSet(sample_id = sampid[:4], variant_id = varid[:6])

Get data from the subset of variant data

In [6]:
f.GetData("chromosome")

array(['22', '22', '22', '22', '22', '22'], dtype=object)

In [7]:
f.GetData("allele")

array(['A,G', 'G,A', 'G,T', 'C,T', 'G,A', 'G,A'], dtype=object)

In [8]:
geno = f.GetData("genotype")
geno.shape

(6, 4, 2)

In [9]:
geno

array([[[0, 0],
        [1, 0],
        [1, 0],
        [0, 1]],

       [[0, 0],
        [0, 1],
        [0, 1],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [1, 0],
        [0, 1],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=uint8)

In [10]:
dosage = f.GetData("$dosage")
dosage.shape

(6, 4)

In [11]:
dosage

array([[2, 1, 1, 1],
       [2, 1, 1, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 1, 1, 2],
       [2, 2, 2, 2]], dtype=uint8)